baseURL = "http://localhost:1313"

[params.services]
analyticsId = "UA-DEV"
adwordsId = "AW-DEV"
adsenseId = ""
adsenseAdSlotId = ""
adwordsConversionId = "ID-DEV"
adwordsConversionValue = 0
facebookApp = "FB-DEV"
facebookPixel = "FB-DEV"
disqusShortname = ""

[params.cdn]
provider = "cloudinary"
[params.cloudinary]
host = "https://res.cloudinary.com/jwcom/"
version = ""
